apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: siboscol/udagram-api-user:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
